version: '3.9'

volumes:
  external:

x-default-app: &default_app
  build: .
  image: hopsoft/trix_embed
  stdin_open: true
  tty: true
  volumes:
    - .:/app
    - external:/mnt/external
  environment:
    DOCKER_CONTAINER: true
    YARN_CACHE_FOLDER: /mnt/external/yarn/.cache

services:
  web:
    <<: *default_app
    container_name: trix_embed-web
    ports:
      - 3000:3000
    command: yarn dev
    healthcheck:
      test:
        ['CMD', 'curl', '--silent', '--fail', 'http://localhost:3000']
      interval: 30s
      timeout: 30s
      retries: 10

  esbuild:
    <<: *default_app
    container_name: trix_embed-esbuild
    command: /bin/bash -c "yarn build --watch"
