// This file is auto-generated by bin/build.mjs
export default {
  author: 'Nate Hopkins (hopsoft) <natehop@gmail.com>',
  copyright: 'Copyright © 2023 Nate Hopkins (hopsoft) <natehop@gmail.com>',
  description: 'A Stimulus controller to safely embed external media in the Trix editor',
  license: 'MIT',
  repository: 'https://github.com/hopsoft/trix_embed',
  version: '0.0.2'
}
